### PR TITLE
fix(cosh-ng): [core] support macOS reads

### LINKED ISSUE #2164: [cosh-ng] core: macOS build broken since c818e118 — workspace_fs uses Linux-only openat2/ResolveFlags without platform gating
### Summary

Since commit `c818e118` ("fix(cosh-ng): [core] confine read tools"), `cosh-core` no longer compiles on macOS. The new `crates/cosh-core/src/tool/workspace_fs.rs` uses Linux-only rustix APIs (`openat2`, `ResolveFlags`, `OFlags::PATH`) without any platform gating, and the module is consumed unconditionally by the core read tools (`grep.rs`, `glob.rs`, `list_directory.rs`, `file_patterns.rs`), so the whole crate fails to build.

CI stayed green because the workflow matrix only has Linux runners (`anolisa-k8s-*` / ubuntu); macOS is a developer-local build target and had been building fine right up to the parent of `c818e118` (verified locally at `12ea0ad9`).

### Reproduction

On macOS (verified on darwin arm64, workspace toolchain):

```
cargo build -p cosh-core
```

```
error[E0432]: unresolved imports `rustix::fs::openat2`, `rustix::fs::ResolveFlags`
   --> crates/cosh-core/src/tool/workspace_fs.rs:13:18
    |
 13 | use rustix::fs::{openat2, readlinkat, Dir, FileType, Mode, OFlags, ResolveFlags, CWD};
    |                  ^^^^^^^ no `openat2` in `fs`                      ^^^^^^^^^^^^ no `ResolveFlags` in `fs`

error[E0599]: no associated function or constant named `PATH` found for struct `OFlags`
  --> crates/cosh-core/src/tool/workspace_fs.rs:27:35
    |
 27 | const PIN_FLAGS: OFlags = OFlags::PATH.union(OFlags::CLOEXEC).union(OFlags::NOFOLLOW);

error[E0599]: no associated function or constant named `PATH` found for struct `OFlags`
   --> crates/cosh-core/src/tool/workspace_fs.rs:200:21
    |
200 |             OFlags::PATH | OFlags::DIRECTORY | OFlags::CLOEXEC,
```

`cosh-shell` still builds fine on macOS; only `cosh-core` is affected. Previously built cosh-core binaries keep running — the breakage is compile-time only.

### Impact

- Building cosh-core from source on macOS is impossible at HEAD (no feature flag or workaround; `mod workspace_fs` and its consumers have no `cfg` gating).
- Any workflow that needs an up-to-date local cosh-core binary on macOS (development, real-adapter reproduction/acceptance evidence) is blocked and must fall back to Linux environments.

### Notes on fixing

This is not a one-line `cfg` fix. `workspace_fs` relies on `openat2(RESOLVE_BENEATH | NO_MAGICLINKS | NO_XDEV)` for workspace read confinement, and macOS has no equivalent syscall. A non-Linux fallback needs an explicit security-semantics decision, e.g.:

- component-by-component `openat` walk with `O_NOFOLLOW` (+ manual symlink budget, which the module already tracks via `MAX_SYMLINKS`), or
- a weaker canonicalize-and-prefix-check fallback, documented as best-effort on non-Linux.

Either way the chosen boundary for non-Linux platforms should be stated explicitly rather than silently diverging from the Linux guarantees.

Optionally, a lightweight `cargo check -p cosh-core --target aarch64-apple-darwin` (or a macOS runner smoke job) would catch this class of regression before merge.

### PR DESCRIPTION
**Pull request by kongche-jbw**
## Why

Commit `c818e118` confined read tools with Linux-only `openat2` APIs and
`/proc/self/fd`, which prevents `cosh-core` from compiling on macOS. This
change restores macOS development while preserving Linux confinement.

## What changed

- Keep the Linux `openat2` implementation unchanged behind platform gates.
- Add a macOS best-effort fallback using canonical paths, workspace-prefix
  checks, same-device enforcement, and post-open `dev`/`ino` verification.
- Fail closed when the pinned macOS workspace root is replaced, and cover
  platform-specific confinement behavior and `.git` file markers in tests.

## Related issue

Closes #2164

## User / Agent impact

`cosh-core` and its workspace read tools build and run on macOS again. Linux
continues to use its existing kernel-enforced `openat2` path.

## Risk and compatibility

- [ ] Public CLI, API, configuration, or documented behavior changed
- [x] Privileged or security-sensitive behavior changed
- [ ] Cross-component contract changed
- [ ] Migration or rollback guidance is needed

The Linux security path is unchanged. The macOS fallback is explicitly
best-effort because path resolution and opening are not one atomic operation.
macOS also lacks `O_PATH`, so metadata-only access to unreadable files and
search-only directories can fail. Canonical paths may render `/var` as
`/private/var`, and root replacement fails closed instead of continuing through
the pinned descriptor.

## Validation

- `cargo fmt --all -- --check`
- `cargo build --locked -p cosh-core`
- `cargo test --locked -p cosh-core` — all targets passed on macOS; library
  97/97, binary 781/781, and all integration targets passed
- `cargo clippy --locked -p cosh-core --all-targets -- -D warnings`

## Documentation and rollback

No documentation files changed. Revert this commit to restore the Linux-only
behavior; macOS builds will again be unsupported.

### CODE REVIEW

File: src/cosh-ng/crates/cosh-core/src/tool/workspace_fs.rs [hunk 1]
```diff
@@ -926,6 +1096,30 @@ impl WorkspaceFs {
...
+    fn git_marker(
+        &self,
+        relative_directory: &Path,
+    ) -> Result<Option<GitMarker>, WorkspaceOpenError> {
+        let marker_path = relative_directory.join(".git");
+        let Some(marker) = self.pin_beneath(&marker_path)? else {
+            return Ok(None);
+        };
+        marker
+            .metadata()
```
[the remark this answers is not in the document]
Comment (kongche-jbw) [reply src/cosh-ng/crates/cosh-core/src/tool/workspace_fs.rs]: 已在 `bc4fdba8` 处理：新增跨平台 `git_file_marks_worktree_as_a_repository` 端到端测试，使用普通 `.git` 文件验证其会建立仓库边界、加载 `.gitignore`，同时保留未忽略文件。macOS 全量 `cosh-core` 测试已通过。

**Review by SunnyQjm — APPROVED** [review]
LGTM
